version: '3.8'
services:
  mysql:
    container_name: mysql
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: test-db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
    networks:
      - infra

  backend:
    container_name: backend
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    networks:
      - infra

networks:
  infra:
    driver: bridge